finalproject/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_comm');

Route::resource('conference', 'ConferenceController');

Route::resource('paper', 'PaperController');

Route::get('log', [
    'as' => 'log.index',
    'uses' => 'LogController@index'
]);

Route::get('log/{filename}', [
    'as' => 'log.show', 
    'uses' => 'LogController@show'
]);

finalproject/app/Conference.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Conference extends Model
{
    protected $fillable = [
        'session',
		'email',
		'presentopt',
		'fees',
		'paymentopt',
		'paymentstatus',
		'attendence'
    ];

}

finalproject/app/Http/Controllers/ConferenceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Conference;

class ConferenceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $conferences = Conference::all();
	   return view('conference.index', compact('conferences'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('conference.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'session'=>'required',
            'email'=>'required',
			'presentopt'=>'required',
			'fees'=>'required',
			'paymentopt'=>'required',
			'paymentstatus'=>'required'
        ]);
		
		$conference = new Conference([
            'session' => $request->get('session'),
            'email' => $request->get('email'),
            'presentopt' => $request->get('presentopt'),
            'fees' => $request->get('fees'),
            'paymentopt' => $request->get('paymentopt'),
			'paymentstatus'=>$request->get('paymentstatus')
        ]);

		$conference->save();
        return redirect('/home')->with('success', 'Details saved!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $conference = Conference::find($id);
        return view('conference.edit', compact('conference'));        

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'paymentstatus'=>'required'
        ]);

        $conference = Conference::find($id);
        $conference->session =  $request->get('session');
        $conference->email = $request->get('email');
        $conference->presentopt = $request->get('presentopt');
        $conference->fees = $request->get('fees');
        $conference->paymentopt = $request->get('paymentopt');
        $conference->paymentstatus = $request->get('paymentstatus');
		$conference->attendence = $request->get('attendece');
        $conference->save();

        return redirect('/conference')->with('success', 'Details updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
		$conference = Conference::find($id);
        $conference->delete();
				
        return redirect('/conference')->with('success', 'Details deleted!');
    }
}

finalproject/resources/views/conference/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
	<br>
	<br>
    <h1 style="text-align:center;">Join a conference</h1>
	<hr>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('conference.store') }}">
          @csrf
          
		  <div class="form-group">
              <label for="email"> Email: </label>
              <input type="text" class="form-control" name="email"/>
          </div>
		  
		  <div class="form-group">
              <label for="session"> Session: </label>
			  <br>
              <select name="session">
				<option value="indust4"> Indusry 4.0 and Beyond </option>
				<option value="businfo"> Business Informatics and Industry 4.0 </option>
				<option value="softemerge"> Software Systems and Emerging Technologies Communications Network and Industry 4.0 </option>
			  </select>
          </div>

          <div class="form-group">
				<label for="presentopt"> Present Option: </label>
				<br>
				<select name="presentopt">
					<option value="physical"> Physical Presentation </option>
					<option value="online"> Online Presentation </option>
				</select>
          </div>
		  
          <div class="form-group">
              <label for="fees"> Fees: </label>
			  <br>
			  <select name="fees">
					<option value="nonmember"> Normal (Non-Member IEEE)- RM2200 or USD530 </option>
					<option value="member"> IEEE Member - RM2000 or USD480 </option>
					<option value="student"> Student - RM1600 or USD385 </option>
			  </select>
          </div>
		
          <div class="form-group">
              <label for="paymentopt"> Payment Option: </label>
			  <br>
			  <select name="paymentopt">
					<option value="maybank"> Maybank2U </option>
					<option value="cimb"> CIMBClicks </option>
					<option value="tng"> TNG E Wallet </option>
			  </select>
          </div>

		  <input type="hidden" name="paymentstatus" value="pending"></input>
		  
		  <br>
          <button type="submit" class="btn btn-primary" style="margin:auto; display:block;"> Submit </button>
      
	  </form>
  </div>
</div>
</div>
@endsection

finalproject/resources/views/conference/edit.blade.php
@extends('base') 
@section('main')
<br>
<br>
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 style="text-align:center;"> Update Participant Status </h1>
		<hr>
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('conference.update', $conference->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="session"> Session: </label>
                <input type="text" class="form-control" name="session" value={{ $conference->session }} readonly />
            </div>

            <div class="form-group">
                <label for="email"> Email: </label>
                <input type="text" class="form-control" name="email" value={{ $conference->email }} readonly />
            </div>

            <div class="form-group">
                <label for="presentopt"> Present Option: </label>
                <input type="text" class="form-control" name="presentopt" value={{ $conference->presentopt }} readonly />
            </div>
			
            <div class="form-group">
                <label for="city"> Fees: </label>
                <input type="text" class="form-control" name="fees" value={{ $conference->fees }} readonly />
            </div>
			
            <div class="form-group">
                <label for="paymentopt"> Payment Option: </label>
                <input type="text" class="form-control" name="paymentopt" value={{ $conference->paymentopt }} readonly />
            </div>
			
            <div class="form-group">
                <label for="paymentstatus"> Payment Status: </label>
                <br>
				<select name="paymentstatus">
					<option value="pending"> Pending </option>
					<option value="accept"> Accept </option>
				</select>
            </div>
			
			<div class="form-group">
				<label for="attendence"> Attendence: </label>
				<br>
				<select name="attendence">
					<option value=""> </option>
					<option value="attend"> Attend </option>
					<option value="not attend"> Not Attend </option>
				</select>
			</div>
			
            <button type="submit" class="btn btn-primary" style="margin:auto; display:block;">Update</button>
        
		</form>
    </div>
</div>
@endsection

finalproject/resources/views/conference/index.blade.php
@extends('base')

@section('main')
<br>
<br>
<div class="row">
<div class="col-sm-12">
  <h1 style="text-align:center;">Participant Details</h1>
  <div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
  </div>
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Session</td>
          <td>Email</td>
          <td>Present Option</td>
          <td>Fees</td>
          <td>Payment Option</td>
		  <td>Payment Status</td>
		  <td>Attendence</td>
		  <td> Update Status </td> 
		  <td> Reject Request </td> 
        </tr>
    </thead>
    <tbody>
        @foreach($conferences as $conference)
        <tr>
            <td> {{$conference->id}} </td>
            <td> {{$conference->session}} </td>
            <td> {{$conference->email}} </td>
            <td> {{$conference->presentopt}} </td>
            <td> {{$conference->fees}} </td>
            <td> {{$conference->paymentopt}} </td>
			<td><b style="color:gray;"> {{$conference->paymentstatus}} </b></td>
			<td> {{$conference->attendence}} </td>
			<td>
                <a href="{{ route('conference.edit',$conference->id)}}" class="btn btn-primary"> Edit </a>
            </td>

			
			<td>
                <form action="{{ route('conference.destroy', $conference->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit"> Remove </button>
                </form>
            </td>

			
        </tr>
        @endforeach
    </tbody>
  </table>
</div>
</div>
@endsection