finalproject/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_comm');

Route::resource('conference', 'ConferenceController');

Route::resource('paper', 'PaperController');

Route::get('log', [
    'as' => 'log.index',
    'uses' => 'LogController@index'
]);

Route::get('log/{filename}', [
    'as' => 'log.show', 
    'uses' => 'LogController@show'
]);

finalproject/app/Paper.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Paper extends Model
{
    protected $fillable = [
        'paperbground',
		'papertype',
		'papername',
		'email',
		'status'
    ];

}

finalproject/app/Http/Controllers/PaperController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Paper;

class PaperController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $papers = Paper::all();
		return view('paper.index', compact('papers'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('paper.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'paperbground'=>'required',
            'papertype'=>'required',
			'papername'=>'required',
            'email'=>'required'
        ]);

        $paper = new Paper([
            'paperbground' => $request->get('paperbground'),
            'papertype' => $request->get('papertype'),
            'papername' => $request->get('papername'),
            'email' => $request->get('email'),
			'status' => $request->get('status')
        ]);
		
		$paper->save();
        return redirect('/home')->with('success', 'Details saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $paper = Paper::find($id);
        return view('paper.edit', compact('paper'));        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'status'=>'required'
        ]);

        $paper = Paper::find($id);
        $paper->paperbground =  $request->get('paperbground');
		$paper->papertype =  $request->get('papertype');
		$paper->papername =  $request->get('papername');
		$paper->email =  $request->get('email');
		$paper->status =  $request->get('status');
        $paper->save();

        return redirect('/paper')->with('success', 'Details updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $paper = Paper::find($id);
        $paper->delete();
				
        return redirect('/paper')->with('success', 'Details deleted!');
    }
}

finalproject/resources/views/paper/create.blade.php
@extends('papbase')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
	<br>
	<br>
    <h1 style="text-align:center;"> Upload Research Paper </h1>
	<hr>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('paper.store') }}">
          @csrf
		  <div class="form-group">
              <label for="papertype"> Research Publication: </label>
			  <br>
              <select name="papertype">
				<option value="journal"> IEE Journal </option>
				<option value="magazine"> IEEE Magazine </option>
				<option value="proceeding"> IEEE Conference Proceedings </option>
				<option value="book"> IEE Books </option>
			  </select>
          </div>
		  
          <div class="form-group">    
              <label for="paperbground"> Research Background: </label>
              <input type="text" class="form-control" name="paperbground"/>
          </div>

          <div class="form-group">
              <label for="papername"> Research Paper Topic: </label>
              <input type="text" class="form-control" name="papername"/>
          </div>
		  
		  <div class="form-group">
              <label for="email">Email:</label>
              <input type="text" class="form-control" name="email"/>
          </div>
		  
		  <input type="hidden" name="status" value="pending"></input>
		  
		  <br>
          <button type="submit" class="btn btn-primary" style="margin:auto; display:block;"> Submit </button>
      
	  </form>
  </div>
</div>
</div>
@endsection

finalproject/resources/views/paper/edit.blade.php
@extends('base') 
@section('main')
<br>
<br>
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 style="text-align:center;"> Update Research Paper Status </h1>
		<hr>
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('paper.update', $paper->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="paperbground"> Research Paper Background: </label>
                <input type="text" class="form-control" name="paperbground" value={{ $paper->paperbground }} readonly />
            </div>

            <div class="form-group">
                <label for="papertype"> Research Paper Type: </label>
                <input type="text" class="form-control" name="papertype" value={{ $paper->papertype }} readonly />
            </div>

            <div class="form-group">
                <label for="papername"> Research Paper Topic: </label>
                <input type="text" class="form-control" name="papername" value={{ $paper->papername }} readonly />
            </div>
			
            <div class="form-group">
                <label for="email"> Email: </label>
                <input type="text" class="form-control" name="email" value={{ $paper->email }} readonly />
            </div>
			
			<div class="form-group">
				<label for="status"> Research Paper Status: </label>
				<br>
				<select name="status">
					<option value="pending"> Pending </option>
					<option value="verified"> Verified </option>
				</select>
			</div>
		   
            <button type="submit" class="btn btn-primary" style="margin:auto; display:block;">Update</button>
        
		</form>
    </div>
</div>
@endsection

finalproject/resources/views/paper/index.blade.php
@extends('base')

@section('main')
<br>
<br>
<div class="row">
<div class="col-sm-12">
  <h1 style="text-align:center;"> Research Paper Details </h1>
  <div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
  </div>
  <table class="table table-striped">
    <thead>
        <tr>
          <td> ID </td>
          <td> Research Paper Background </td>
          <td> Research Paper Type </td>
          <td> Research Paper Topic </td>
		  <td> Email </td>
		  <td> Research Paper Status </td>
		  <td> Update Status </td>
		  <td> Reject Paper </td>	
        </tr>
    </thead>
    <tbody>
        @foreach($papers as $paper)
        <tr>
            <td> {{$paper->id}} </td>
            <td> {{$paper->paperbground}} </td>
            <td> {{$paper->papertype}} </td>
            <td> {{$paper->papername}} </td>
            <td> {{$paper->email}} </td>
            <td><b style="color:gray;"> {{$paper->status}} </b></td>
			<td>
                <a href="{{ route('paper.edit',$paper->id)}}" class="btn btn-primary"> Edit </a>
            </td>

			
			<td>
                <form action="{{ route('paper.destroy', $paper->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit"> Remove </button>
                </form>
            </td>
			
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
</div>
@endsection